### PR TITLE
Fix the handling of readyness conditions of endpointslices

### LINKED ISSUE #2336: Not announce Service if Endpoint is not available, but service marked to publishNotReadyAddresses
### MetalLB Version

0.14.3

### Deployment method

Charts

### Main CNI

cilium

### Kubernetes Version

1.28.5

### Cluster Distribution

cluster-api

### Describe the bug

l2 don't announce IPs for Services with publishNotReadyAddresses:true, if pod isn't running fully.

With 0.13.12, it did work and with 0.14.3, it don't work.

### To Reproduce

1. Create a Service with publishNotReadyAddresses: true
2. Start Pod which is not ready until IP is announced and used.

### Expected Behavior

IP get's announced.

### Additional Context

```
{"caller":"layer2_controller.go:82","event":"shouldannounce","ips":["ip"],"level":"debug","message":"failed no active endpoints","pool":"default","protocol":"l2","service":"namespace/name","ts":"2024-03-26T10:51:13Z"}
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #2336

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix the handling of readyness conditions of endpointslices: instead of looking at the serving condition first, we look at the ready condition. This allows metallb to respect the publishNotReadyAddresses field of the services.
```

### CODE REVIEW

**Comment by farodin91** [comment]
@fedepaol Would you like to review this? It's preventing us from upgrading to 0.14.3.

File: speaker/layer2_controller_test.go [hunk 1]
```diff
@@ -222,10 +224,42 @@ func TestUsableNodesEPSlices(t *testing.T) {
...
+				{
+					Endpoints: []discovery.Endpoint{
+						{
+							Addresses: []string{
+								"2.3.4.5",
+							},
+							NodeName: ptr.To("iris1"),
+							Conditions: discovery.EndpointConditions{
+								Ready:   ptr.To(true),
+								Serving: ptr.To(true),
```
Comment (cyclinder) [inline speaker/layer2_controller_test.go:240]: All of the endpoint's serving is true, It looks like your tests and descriptions are consistent.

**Comment by farodin91** [comment]
@cyclinder fixed.

**Comment by aojea** [comment]
You don't need to use the boolean from the Service , you just need to parse the Slice conditions correctly, see how it has to be done https://github.com/cilium/cilium/pull/24174/files

**Comment by farodin91** [comment]
@aojea I changed the behavior.

File: internal/k8s/epslices/endpoint_slices.go [hunk 2]
```diff
@@ -11,16 +11,13 @@ import (
...
-func IsConditionServing(conditions discovery.EndpointConditions) bool {
-	if conditions.Serving == nil {
-		if conditions.Ready == nil {
-			return true
-		}
-		return *conditions.Ready
+// IsConditionReady tells if the conditions represent a ready state, deferring
+// to serving state if ready == false.
+func IsConditionReady(conditions discovery.EndpointConditions) bool {
+	if !(conditions.Ready == nil || *conditions.Ready) {
```
Comment (fedepaol) [inline internal/k8s/epslices/endpoint_slices.go:17]: I am having a hard time parsing this. Can you unroll the if and have each exit point separate (or just take inspiration to what cilium does?)

File: speaker/layer2_controller_test.go [hunk 3]
```diff
@@ -222,6 +222,37 @@ func TestUsableNodesEPSlices(t *testing.T) {
 			usableSpeakers:  map[string]bool{"iris1": true, "iris2": true},
 			cExpectedResult: []string{"iris1", "iris2"},
 		},
+		{
+			desc: "Two endpoints, different hosts, ready but not serving",
```
Comment (fedepaol) [inline speaker/layer2_controller_test.go:226]: we should cover also the bgp side

File: internal/k8s/epslices/endpoint_slices.go [hunk 4]
```diff
@@ -11,16 +11,13 @@ import (
...
-// to ready state if serving == nil.
-func IsConditionServing(conditions discovery.EndpointConditions) bool {
-	if conditions.Serving == nil {
-		if conditions.Ready == nil {
-			return true
-		}
-		return *conditions.Ready
+// IsConditionReady tells if the conditions represent a ready state, deferring
+// to serving state if ready == false.
+func IsConditionReady(conditions discovery.EndpointConditions) bool {
```
Comment (fedepaol) [inline internal/k8s/epslices/endpoint_slices.go:16]: given this is going to be a bit more complex, can we add a unit tests to cover the various cases?

**Comment by fedepaol** [comment]
@farodin91 now that we are converging on the solution, please also adjust the commit messages with the reason why we are applying the change and what we are changing. Good reference is https://cbea.ms/git-commit/

File: internal/k8s/epslices/endpoint_slices.go [hunk 5]
```diff
@@ -11,16 +11,11 @@ import (
...
-func IsConditionServing(conditions discovery.EndpointConditions) bool {
-	if conditions.Serving == nil {
-		if conditions.Ready == nil {
-			return true
-		}
-		return *conditions.Ready
-	}
-	return *conditions.Serving
+// IsConditionReadyOrServing tells if the conditions represent a ready state or serving state is ready.
+func IsConditionReadyOrServing(conditions discovery.EndpointConditions) bool {
```
Comment (fedepaol) [inline internal/k8s/epslices/endpoint_slices.go:15]: I think this can be untangled a bit more, with something like:

```go
/ IsConditionReadyOrServing tells if the conditions represent a ready state or serving state is ready.
func IsConditionReadyOrServing(conditions discovery.EndpointConditions) bool {
        if conditions.Ready == nil || *conditions.Ready {
                return true
        }
        if conditions.Serving != nil && *conditions.Serving {
                return true
        }
        return false
}
```

I'd also rename to endpointCanServe as it is the semantic we are looking for

File: internal/k8s/epslices/endpoint_slices_test.go [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+		{
+			name: "Is Ready but not serving",
+			conditions: v1.EndpointConditions{
+				Ready:   ptr.To(true),
+				Serving: ptr.To(false),
+			},
+			want: true,
+		},
+		{
+			name:       "Not set Ready and serving",
```
Comment (fedepaol) [inline internal/k8s/epslices/endpoint_slices_test.go:38]:
```suggestion
			name:       "Ready and Serving not set",
```

File: internal/k8s/epslices/endpoint_slices_test.go [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+			conditions: v1.EndpointConditions{},
+			want:       true,
+		},
+		{
+			name: "Not set Ready but not serving",
```
Comment (fedepaol) [inline internal/k8s/epslices/endpoint_slices_test.go:43]:
```suggestion
			name: "Ready not set and not serving",
```

**Comment by fedepaol** [comment]
Left a few comments, looks good overall!

You should also fix the failing linting and add a test on the bgp_controller side as you did here https://github.com/metallb/metallb/pull/2337#discussion_r1559007128

**Comment by farodin91** [comment]
@fedepaol Everything should be changed.

**Comment by fedepaol** [comment]
@farodin91 LGTM!
I have one final ask (thanks for the patience :-) )
Can you adjust the commit subj / message? What I put in the release notes should be good

```
Fix the handling of readyness conditions of endpointslices

instead of looking at the serving condition first, we look at the ready condition which has precendence. This allows metallb to respect the publishNotReadyAddresses field of the services.
```

Thanks again!

**Comment by farodin91** [comment]
@fedepaol Updated.

**Comment by fedepaol** [comment]
> @fedepaol Updated.

thanks! Sending to merge queue
