### PR TITLE
#364: Reject service IPs overlap with node IPs

### LINKED ISSUE #364: Detect and reject configurations where the service IP range overlaps with node IPs
Probably due to inadequate documentation, people think that they can define service IPs that overlap with node IPs. This breaks things in multiple ways (ARP poisoning in L2 mode, wrong kube-proxy rules executed in all modes...), and is not at all a supported mode of operation.

The controller should detect and reject such configurations, as well as refuse to allocate IPs if they overlap with node IPs.

### PR DESCRIPTION
**Pull request by tyiying**
**Is this a BUG FIX or a FEATURE ?**: BUG FIX #364

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression

**What this PR does / why we need it**:
Probably due to inadequate documentation, people think that they can define service IPs that overlap with node IPs. This breaks things in multiple ways (ARP poisoning in L2 mode, wrong kube-proxy rules executed in all modes...), and is not at all a supported mode of operation.
This PR add a webhook validation to check IPAddressPool IP range, if it is overlap with node IPs, reject the configuration of IPAddressPool

**Special notes for your reviewer**:
- Webhook validation rejection for IPAddressPool has explicit error message so it is easy for user to adjust the configuration. Also webhook validation on IPAddressPool does the rejection before automatic IP allocation take place at service configuration stage. 

**Release note**:
```release-note
Don't allow IPAddressPools providing IPs overlapping with node IPs.
```

### CODE REVIEW

File: controller/service.go [hunk 1]
```diff
@@ -220,6 +221,16 @@ func (c *controller) allocateIPs(key string, svc *v1.Service) ([]net.IP, error)
...
 			return nil, fmt.Errorf("requested loadBalancer IP(s) %q does not match the ipFamily of the service", desiredLbIPs)
 		}
+
+		nodes := []v1.Node{}
+		for _, node := range c.nodes {
+			nodes = append(nodes, *node)
+		}
+
+		nodeIPs := k8snodes.NodeIPsForFamily(nodes, serviceIPFamily)
+		if err = checkSvcIPsOverlapWithNodeIPs(desiredLbIPs, nodeIPs); err != nil {
```
Comment (fedepaol) [inline controller/service.go:231]: I would argue that this will never happen, because even if the service asks for a node ip, that ip will never be available in a pool. Let's remove the controller bits and focus only on the configuration part.

File: controller/main.go [hunk 2]
```diff
@@ -147,6 +148,11 @@ func (c *controller) SetPools(l log.Logger, pools *config.Pools) controllers.Syn
 	return controllers.SyncStateReprocessAll
 }
 
+func (c *controller) SetNode(l log.Logger, node *v1.Node) controllers.SyncState {
+	c.nodes[node.Name] = node
```
Comment (fedepaol) [inline controller/main.go:152]: nit: although I am asking to remove this, writing it to let you know that we should be careful to consider that this map is not aligned with the content of the informer cache, and only expands. If a node gets removed, its ips will still be not valid.

**Review by fedepaol — COMMENTED** [review]
Looks good! Just a nit on redundant check over the service ip that can be simplified.

**Comment by fedepaol** [comment]
Also (but in this case is not that bad because the code is quite compact), in general we try to separate the pr in various commits, the most straightforward being splitting the logic from the e2es

File: controller/service.go (hunk 1 above)
Comment (tyiying) [reply controller/service.go:231]: ok. will remove.

File: controller/main.go (hunk 2 above)
Comment (tyiying) [reply controller/main.go:152]: I see. As long as the removed nodes' IP aren't made available in the pool for the services, there won't be any risk of conflict.

File: controller/service.go (hunk 1 above)
Comment (tyiying) [reply controller/service.go]: This comment is resolved. Checking for service LB ip against node IPs is removed.

File: controller/main.go (hunk 2 above)
Comment (tyiying) [reply controller/main.go]: Comment is resolved. Code is removed.

File: e2etest/webhookstests/webhooks.go [hunk 3]
```diff
@@ -106,6 +113,51 @@ var _ = ginkgo.Describe("Webhooks", func() {
...
+		ginkgo.DescribeTable("IPAddressPool with overlapping addresses of the nodes",
+			func(ipFamily ipfamily.Family) {
+				nodes, err := cs.CoreV1().Nodes().List(context.Background(), metav1.ListOptions{})
+				Expect(err).NotTo(HaveOccurred())
+				nodeIps, err := k8s.NodeIPsForFamily(nodes.Items, ipFamily, "")
+				Expect(err).NotTo(HaveOccurred())
+				for _, nodeIPString := range nodeIps {
+					nodeIP := net.ParseIP(nodeIPString)
+					var nodeCIDRs []string
+					if nodeIP.To4() != nil {
```
Comment (fedepaol) [inline e2etest/webhookstests/webhooks.go:126]: we now the family already, no need to do this if. Also, it should be enough just to pick the first node, no need to iterate over all

**Comment by fedepaol** [comment]
one small nit and I think it's good to go! Thanks!

File: e2etest/webhookstests/webhooks.go (hunk 3 above)
Comment (tyiying) [reply e2etest/webhookstests/webhooks.go:126]: not sure I understand you. do you mean this if check at line 126? This check is needed to differentiate ipv4 and ipv6 since they have different CIDRMask. 

I agree, we don't need to iterate all nodes ip, first one is enough. will change.

File: e2etest/webhookstests/webhooks.go [hunk 4]
```diff
@@ -106,6 +113,51 @@ var _ = ginkgo.Describe("Webhooks", func() {
...
+								Spec: metallbv1beta1.IPAddressPoolSpec{
+									Addresses: nodeCIDRs,
+								},
+							},
+						},
+					}
+					err = ConfigUpdater.Update(resources)
+					Expect(err).To(HaveOccurred())
+					Expect(err.Error()).To(ContainSubstring("contains nodeIp"))
+					break
```
Comment (tyiying) [inline e2etest/webhookstests/webhooks.go:155]: here I break out the loop after the first node.

File: e2etest/webhookstests/webhooks.go (hunk 3 above)
Comment (fedepaol) [reply e2etest/webhookstests/webhooks.go:126]: what I mean is, we have ipFamily as parameter, so instead of parsing the node ip and trying to understand if it's v4 or v6, we should rely on that.

File: e2etest/webhookstests/webhooks.go (hunk 4 above)
Comment (fedepaol) [reply e2etest/webhookstests/webhooks.go:155]: but then why building the nodCIDRs? It's always going to be one right?

Comment (fedepaol) [reply e2etest/webhookstests/webhooks.go:155]: or, even doing the loo in first instance, if we always break

File: e2etest/webhookstests/webhooks.go (hunk 3 above)
Comment (tyiying) [reply e2etest/webhookstests/webhooks.go:126]: ok. what happen if ipfamily is ipfamily.DualStack? it could return both ipv4 and ipv6 nodeIPs.

Comment (fedepaol) [reply e2etest/webhookstests/webhooks.go:126]: ipfamily is a parameter we are driving here, and we have only v4 and v6 iiuc

Comment (fedepaol) [reply e2etest/webhookstests/webhooks.go:126]: I mean ipFamily is what you are setting here, https://github.com/metallb/metallb/pull/2585/files#diff-d32fb1c70f00b7179f34c7f6d38e974556efc26ffa22cc0d808991e07f13140eR158 in line 158

File: e2etest/webhookstests/webhooks.go (hunk 4 above)
Comment (tyiying) [reply e2etest/webhookstests/webhooks.go:155]: agree. I will change.

File: e2etest/webhookstests/webhooks.go [hunk 5]
```diff
@@ -106,6 +113,50 @@ var _ = ginkgo.Describe("Webhooks", func() {
...
+						},
+					}
+					err = ConfigUpdater.Update(resources)
+					Expect(err).To(HaveOccurred())
+					Expect(err.Error()).To(ContainSubstring("contains nodeIp"))
+				}
+			},
+			ginkgo.Entry("IPV4", ipfamily.IPv4),
+			ginkgo.Entry("IPV6", ipfamily.IPv6),
+			ginkgo.Entry("DUALSTACK", ipfamily.DualStack),
```
Comment (fedepaol) [inline e2etest/webhookstests/webhooks.go:158]: I don't think there's value in testing dualstack here (plus nodesip[0] is always ipv4)

**Comment by fedepaol** [comment]
@tyiying I took the liberty to apply the last couple of changes myself, as all the work was done and I wanted to push this forward.
Sending to the merge queue, thanks for the contribution!

**Comment by tyiying** [comment]
> @tyiying I took the liberty to apply the last couple of changes myself, as all the work was done and I wanted to push this forward. Sending to the merge queue, thanks for the contribution!

@fedepaol Thanks! please let me know if anything else need to be done.
