### PR TITLE
Fixed    #2039 Allows for configmaptocrs to modify address pools and BFD profiles if…

### LINKED ISSUE #2039: configmaptocrs can create resources with invalid names
### MetalLB Version

0.13.10

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.24.6

### Cluster Distribution

kubespray

### Describe the bug

When using _configmaptocrs_ on configmaps that have resources with names that are not compatible with K8S, it can generate CR names that are not valid. This introduces an extra manual step for upgrading from 0.12.x to 0.13.x . I believe changing this will facilitate the adoption of 0.13.x in large projects such as Kubespray.

This may happen given that these invalid K8S names are valid for the configmap configuration. These names may include: Uppercase, underscores or length over 63 characters.

### To Reproduce

1. Create a configmap with an IPAddressPool with a name that has uppercase letters and underscores
2. Run it through configmaptocrs
3. The generated file cannot be directly applied to K8S, as it has invalid names

e.g.: The following CM:
`apiVersion: v1
data:
  config: |
    address-pools:
    - addresses:
      - 10.100.19.128/32
      - 10.100.16.153/32
      - 10.100.19.135/32
      - 10.100.16.150/32
      - 10.100.20.117/32
      - 10.100.18.171/32
      - 10.100.20.20/32
      - 10.100.19.7/32
      name: load_Balanced
      protocol: layer2`

Will be converted to:
`# This was autogenerated by MetalLB's custom resource generator.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: load_Balanced
  namespace: metallb-system
spec:
  addresses:
  - 10.100.19.128/32
  - 10.100.16.153/32
  - 10.100.19.135/32
  - 10.100.16.150/32
  - 10.100.20.117/32
  - 10.100.18.171/32
  - 10.100.20.20/32
  - 10.100.19.7/32
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
  - load_Balanced
status: {}
---`

### Expected Behavior

configmaptocrs converts CMs to valid K8S resources, and warns if it needs to change any names in the process.

### Additional Context

I've already made the changes necessary to make this work on my own fork. This modification of the original behavior only happens when a new flag "convert-names" is set to true. It is ready for a PR (complete with new tests). 
https://github.com/Sebastian-RG/metallb/commit/02ef1b96653ae5509d25f4f73ab80a16b7cc065e

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

### PR DESCRIPTION
**Pull request by Sebastian-RG**
… they would not have valid resource names once converted

Thanks for sending a pull request! A few things before we get started:

1. If this is your first time, please read the [contributing guide](https://metallb.universe.tf/community/#contributing)
:heavy_check_mark: 
2. For non-trivial pull requests, please [file an
   issue](https://github.com/metallb/metallb/issues/new) first, and get
   agreement that the change is a good idea, and a general guideline
   for how it should be implemented, before sending code. Large PRs
   that weren't first discussed and agreed upon in an issue won't be
   accepted.
https://github.com/metallb/metallb/issues/2039
3. If the PR fixes a particular bug, please include the words "Fixed
   #<issue number>" in the PR text, so that the bug auto-closes when
   the PR is merged.
Fixed  #2039

### CODE REVIEW

**Comment by Sebastian-RG** [comment]
@oribon Hi! If you have the time, could you approve the workflow so the automated tests can run?

**Comment by oribon** [comment]
> @oribon Hi! If you have the time, could you approve the workflow so the automated tests can run?

sorry was away for a while, done and will review it soon I hope

**Comment by Sebastian-RG** [comment]
Fixed an issue with how the `convertNames` flag was passed that was causing CI to fail. I'm not sure how to fix the [Implicit memory aliasing in for loop](https://github.com/metallb/metallb/actions/runs/5857332084/job/16059582956#step:4:162) one. I don't think I modified those lines.

**Comment by Sebastian-RG** [comment]
Sorry about the mess :sweat:, I'm new to Golang and i was checking for an empty list/string the wrong way. This should work now

**Comment by fedepaol** [comment]
> Sorry about the mess 😓, I'm new to Golang and i was checking for an empty list/string the wrong way. This should work now

no problem, and thanks a lot for the contribution! I will go over it soon

**Comment by Sebastian-RG** [comment]
At least this time the actual unit tests passed :smiling_face_with_tear:. I'll correct what the linter mentions in a minute.

**Comment by Sebastian-RG** [comment]
`gofmt -s` done

**Comment by liornoy** [comment]
@Sebastian-RG we just merged a fix for the static-security-analysis, so can you please rebase this PR?
Also, in order to have an organized and unified git log in this repo we have guidelines for the commit messages format.
The full details can be found in here: https://cbea.ms/git-commit/
But if you don't want to read all of it, the basics are: 
Have a title up to 50 characters, starting with a capital letter,
separate the title from body with a blank line
and wrap the body at 72 characters

**Comment by liornoy** [comment]
@fedepaol I think it's better to have this conversion happen by default. wdyt?

**Comment by fedepaol** [comment]
> @fedepaol I think it's better to have this conversion happen by default. wdyt?

+1 , the old version is useless is the generated name is not valid.

File: configmaptocrs/main.go [hunk 1]
```diff
@@ -149,6 +156,65 @@ func decodeConfigFile(raw []byte) (*configFile, error) {
 	return cf, nil
 }
 
+// convertNamesToK8S gets a configFile object and converts all names
+// in it to names compatible with K8S resources, if necessary.
+func convertNamesToK8S(cf *configFile) error {
+	var err error
+
+	for i := 0; i < len(cf.Pools); i++ {
+		cf.Pools[i].Name, err = formatToK8S(cf.Pools[i].Name, "IpAddressPool")
```
Comment (liornoy) [inline configmaptocrs/main.go:165]: Can we maybe do a simple one-liner regex check on the name to see if it's invalid format before calling it straight away?
i.e. if it's valid continue to next iteration, else it will invoke the formatToK8S

**Comment by liornoy** [comment]
@Sebastian-RG thanks for the fix, looks good, just left one comment from my side

**Comment by Sebastian-RG** [comment]
Regex added as requested

**Comment by liornoy** [comment]
lgtm, thanks!

**Comment by fedepaol** [comment]
sent to merge queue

**Comment by Sebastian-RG** [comment]
Fixed a golangci-lint error, sorry for not checking before pushing
